---
title: "Analysis of vaccine data"
author: "NYX"
date: "2023-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(ggplot2)
library(knitr)

ed_levels <- c(
  "Primary school",
  "Secondary school (age under 15 years old)",
  "GNVQ / GSVQ / GCSE/ SCE standard.",
  "NVQ1, NVQ2",
  "NVQ3/ SCE Higher Grade/ Advanced GNVQ/ GCE A/AS or similar.",
  "NVQ4 / HNC / HND / Bachelor's degree or similar.",           
  "NVQ5 or post-graduate diploma.")

likert_levels <- c("Strongly disagree", "Tend to disagree", "Neither agree nor disagree", "Tend to agree", "Strongly agree")

d_trustvac <- read_csv(file="/Users/niyixin/Desktop/R/vaccine/data.csv",
                       col_types = cols(
                         col_number(),
                         col_factor(),
                         col_factor(ordered = TRUE, levels = ed_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels),
                         col_factor(ordered = TRUE, levels = likert_levels)
                       ))

d_trustvac <- d_trustvac %>%
  mutate(
    across(
      .cols = c(starts_with('gov'), starts_with('vac')),
      .fns = as.numeric,
      .names = '{.col}_coded'
    )
  )
```

# Demographic characteristic

## Age
```{r}
d_trustvac %>%
  summarise(
    n=n(), 
    M = mean(age) %>% round(digits = 2),
    Mdn = median(age),
    SD = sd(age) %>% round(digits = 2))

d_trustvac %>%
  ggplot(aes(x = age)) + geom_histogram(binwidth = 5)
```

## gender
```{r}
d_trustvac %>%
  count(gender_nb)

d_trustvac %>%
  ggplot(aes(x = gender_nb)) + geom_bar()
```

## Highest education
```{r}
d_trustvac %>%
  count(hhedqual)
d_trustvac %>%
  ggplot(aes(x = hhedqual)) + geom_bar() + coord_flip()
```
# Descriptive statistics: Likert items
## 按行查看（add）
```{r}
tibble(d_trustvac$govhonest, 
       as.numeric(d_trustvac$govhonest)) %>%
       kable
```

## 单列清除NA值
```{r}
d_trustvac$vacch_coded%>% median(na.rm = TRUE)
```

## 批量处理每列中位数(视频讲解内容)
```{r}
trustvac_likert_summary <- d_trustvac %>%
  select(ends_with('_coded')) %>%
  lapply(
    median, na.rm = TRUE
  )

d_trustvac_likert_summary <- tibble(
  Item = trustvac_likert_summary %>% names,
  Median = trustvac_likert_summary %>% unlist
)

d_trustvac_likert_summary

d_trustvac_likert_summary %>%
  ggplot(aes(x = Item, y = Median)) + geom_point() + coord_flip()
```
